#!/bin/bash

cd ../../.. 
# stupid python which makes it so you have to just copy this and run directly for now.
ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb GNUARMEMB_TOOLCHAIN_PATH="/Applications/ARM/gcc-arm-none-eabi-10.3-2021.10" /opt/homebrew/bin/python3 -m west build -d build/left -b nice_nano -- -DSHIELD=clog_left
:
cd -


